# Generated by Django 4.2.6 on 2023-10-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_tasks_options_tasks_updatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='isChecked',
            field=models.BooleanField(verbose_name='Is Checked'),
        ),
    ]
